from model.xception import model29_val1

model29_val1.train()
