from model.xception import model128_val2

model128_val2.train()